"""link task to user via firebase_uid

Revision ID: 940b91d335e7
Revises: 702b3768c986
Create Date: 2025-12-14 23:42:14.988490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '940b91d335e7'
down_revision: Union[str, Sequence[str], None] = '702b3768c986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('user_firebase_uid', sa.String(length=128), nullable=False))
    op.drop_constraint(op.f('tasks_ibfk_1'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['user_firebase_uid'], ['firebase_uid'])
    op.drop_column('tasks', 'user_id')
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.add_column('tasks', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_ibfk_1'), 'tasks', 'users', ['user_id'], ['user_id'])
    op.drop_column('tasks', 'user_firebase_uid')
    # ### end Alembic commands ###
